version: "3"

services:
  app:
    extends:
      file: ./deploy/docker/docker-compose.common.yml
      service: app_common
    build:
      context: ./project
      dockerfile: ../deploy/docker/dockerfiles/App.Dockerfile
    volumes:
      - ./project:/var/www/html
    extra_hosts:
      - "${APP_DOMAIN}:host-gateway"
    networks:
      - pizza-network

  nginx:
   extends:
     file: ./deploy/docker/docker-compose.common.yml
     service: nginx_common
   volumes:
     - ./deploy/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
     - ./deploy/nginx/logs/:/var/log/nginx/
     - ./project:/var/www/html
     - ./deploy/nginx/ssl:/etc/nginx/ssl
   env_file:
     - ./.env
   networks:
     - pizza-network

  pgdb:
    extends:
      file: ./deploy/docker/docker-compose.common.yml
      service: pgdb_common
    volumes:
      - ${PG_DB_PATH}:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
    networks:
      - pizza-network

  swagger:
    extends:
      file: ./deploy/docker/docker-compose.common.yml
      service: swagger_common
    volumes:
      - ./documentation/openapi.yaml:/docs/openapi.yaml
    env_file:
      - ./.env
    networks:
      - pizza-network

  certbot:
    image: certbot/certbot
    container_name: certbot_pizza
    volumes:
      - ./deploy/nginx/ssl:/etc/letsencrypt
      - ./project:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/html --deploy-hook \"nginx -s reload\"; done;'"
    networks:
      - pizza-network

networks:
  pizza-network:
    driver: bridge